fincal-railed/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

# # Resource Routes  
# 	resources :users, only: %i(create update destroy)
#   	resources :sessions, only: %i(create)

#   	#Manuall Routes
#   	#Main Routes
  	root 'users#welcome'

#   	#User Routes
#   	get '/user/profile' => 'users#profile'
#   	get '/login' => 'users#login'
#   	get '/signup' => 'users#new'
#     post '/user/updatepassword' => 'users#changePassword'

#     #Sessions Routes
#     get 'session/destroy' => 'sessions#destroy'

#   root 'main#index'
   get '/tvom' => 'accounts#tvom' #, as: :tvom_landing
   get '/tvom/real-time-tvom' => 'accounts#real_time_tvom', as: :real_time_tvom
   post '/tvom/real-time-tvom/real-time-tvom-results' => 'accounts#real_time_tvom_results', as: :real_time_tvom_results

#   resources :accounts 
	post '/tvom/results' => 'accounts#tvom_results', as: :tvom_choice

	get '/about' => 'users#about', as: :about
	
resource :users, only: %i(new create update destroy) do
  resources :accounts
end

#maybe this resource needs to be singular?
resource :sessions, only: [:new, :create, :destroy]




end

fincal-railed/app/models/account.rb
class Account < ApplicationRecord

	belongs_to :user
	validates :name, length: {in: 4..40}, presence: true, uniqueness: true
	validates :category, presence: true
	validates :interest, presence: true
	validates :compounding_periods, presence: true, numericality: {only_integer: true}
	validates :compounding_frequency, presence: true, numericality: {only_integer: true}
	validates :balance, presence: true
	validate :compounding_frequency_must_be_mathematically_valid
	validate :interest_must_be_mathematically_valid
	validate :balance_must_be_mathematically_valid
	
	def calculate_fv
		rounder(balance * interest_factor(interest, compounding_frequency) ** compounding_periods)
	end

	def calculate_pv
		pv = (balance) / interest_factor(interest, compounding_frequency) ** compounding_periods
		return rounder(pv)
	end

	def calculate_fv_annuity
		fv = balance * (interest_factor(interest, compounding_frequency) ** compounding_periods - 1) / interest_decimal(interest, compounding_frequency)
		return rounder(fv)
	end

	def calculate_pv_annuity
		pv = balance * ( (1 - (1 / interest_factor(interest, compounding_frequency) ** compounding_periods) ) / interest_decimal(interest, compounding_frequency))
		return rounder(pv)
	end

	def calculate_simple_interest_rate
		rate = interest / (balance * compounding_periods / 365) * 100
		return rounder(rate)
	end

	def calculate_size_of_annuity_payment
		interest_equalized = convert_interest_rate_to_decimal(interest) / compounding_frequency
		interest_factor = (1 + interest_equalized) ** compounding_periods
		interest_factor_minus_one = interest_factor.to_f - 1
		denominator = interest_factor_minus_one / interest_equalized.to_f
		numerator = balance / denominator
		return rounder(numerator)
	end

	private

	def interest_must_be_mathematically_valid
		unless interest.class == Float || interest.class == Integer
			errors.add(:interest, 'rate can only be a whole or floating point number')
		end
	end

	def balance_must_be_mathematically_valid
		unless balance.class == Float || balance.class == Integer
			errors.add(:balance, 'balance can only be a whole or floating point number')
		end
	end

	def compounding_frequency_must_be_mathematically_valid
		unless compounding_frequency == 1 || compounding_frequency == 2 || compounding_frequency == 4 || compounding_frequency == 12 || compounding_frequency == 365
			errors.add(:compounding_frequency, 'interest can only be compounded annually (1), semiannually (2), quarterly (4), monthly (12) or daily (365)')
		end
	end

	def interest_factor(interest, compounding_frequency)
		interest_factor = (1 + (interest.to_f / 100) / compounding_frequency)
		return interest_factor
	end

	def interest_decimal(interest, compounding_frequency)
		decimal = (interest.to_f / 100) / compounding_frequency
		return decimal
	end

	def rounder(value)
		rounded_value = value.round(2)
		return rounded_value
	end

	def convert_interest_rate_to_decimal(interest)
		return interest.to_f / 100
	end
end

fincal-railed/app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	before_action :require_login
	before_action :require_ownership, only: [:show, :edit, :update, :destroy]

	def index
		unless current_user
			flash[:warning] = "sign up to add an account"
		end
		@accounts = current_user.accounts

		@title = 'All Accounts'
		render :index
	end

	def create
		@title = 'Create New Account'
		@account = Account.new
		@account.user = current_user
		@account.name = params[:account][:name]
		@account.category = params[:account][:category]
		@account.balance = params[:account][:balance]
		@account.interest = params[:account][:interest]
		@account.compounding_frequency = params[:account][:compounding_frequency]
		@account.compounding_periods = params[:account][:compounding_periods]

		#respond_to do |format|
			if @account.save
				UserMailer.with(account: @account, user: current_user).account_email(current_user, @account).deliver_now
				#format.html {redirect_to users_accounts_path}
				redirect_to users_accounts_path
			else
				render :new
			end
		#end
	end

	def new
		@title = 'Create New Account'
		@account = Account.new
	end

	def edit
		id = params[:id]
		@account = Account.find(id)
	end

	def show

		@creation_date = @account.created_at.strftime("%A-%Y-%B-%d")


	end

	def update
		@account.name = params[:account][:name]
		@account.category = params[:account][:category]
		@account.balance = params[:account][:balance]
		@account.interest = params[:account][:interest]
		@account.compounding_frequency = params[:account][:compounding_frequency]
		@account.compounding_periods = params[:account][:compounding_periods]

		if @account.save
			redirect_to users_accounts_path
		else
			render :new
		end
	end

	def destroy
		@account.destroy
		redirect_to users_accounts_path
	end

	def tvom
		@accounts = current_user.accounts
		render :tvom
	end

	def tvom_results
		@result = "you typed the wrong selection"
		#finds the account that the person chooses in the form from params
		@account = current_user.accounts.find(params[:user_choice][:account])
		account_balance = @account.balance
		#assigns the value that the user chooses for the function they want to invoke on the account
		@selection = params[:user_choice][:choice].to_i
		case @selection
			when 1 then @result =  @account.calculate_fv
				@calculation_performed = 'computed future value:'

			when 2 then @result = @account.calculate_pv
				@calculation_performed = 'computed present value:'

			when 3 then @result = @account.calculate_fv_annuity
				@calculation_performed = 'computed future value of the annuity payments:'

			when 4 then @result = @account.calculate_pv_annuity
				@calculation_performed = 'computed present value of the annuity payments:'
		end
		@interest_time = @account.compounding_periods
		@frequency = @account.compounding_frequency
		@interest_portion = @result - account_balance
		
		if @interest_portion 
			UserMailer.with(account: @account, user: current_user).calculation_email(current_user, @account, @result, @interest_portion, @calculation_performed).deliver_now
		end
	end

	def real_time_tvom

	end

	def real_time_tvom_results
		@real_time_account = Account.new

		if params[:compute_interest_rate]
			@real_time_account.interest = params[:compute_interest_rate][:interest_portion]
			@real_time_account.balance = params[:compute_interest_rate][:pv]
			@real_time_account.compounding_periods = params[:compute_interest_rate][:time]
			@computation = @real_time_account.calculate_simple_interest_rate
		end

		if params[:compute_annuity_payment]
		@real_time_account.interest = params[:compute_annuity_payment][:interest_rate]
		@real_time_account.compounding_frequency = params[:compute_annuity_payment][:compounding_frequency]
		@real_time_account.compounding_periods = params[:compute_annuity_payment][:compounding_periods]
		@real_time_account.balance = params[:compute_annuity_payment][:fv]
		
		@computation = @real_time_account.calculate_size_of_annuity_payment
		@earned_amount_interest = params[:compute_annuity_payment][:fv].to_f - (@computation * (params[:compute_annuity_payment][:compounding_periods].to_i))
		end
	end

	private

	def require_ownership
		owner_id = params[:id]
		the_account = Account.find(owner_id)
		if the_account.user == current_user
				@account = Account.find(params[:id])
				@title = @account.name
		else
			redirect_to users_accounts_path
		end
	end
end

fincal-railed/app/helpers/accounts_helper.rb
module AccountsHelper
end

fincal-railed/app/views/accounts/_account_form.html.erb
<% if an_account.errors.any? %> 
<div id="error_explanation">
	<h2><%= pluralize(an_account.errors.count, "error") %> prohibited this account from being saved:</h2>
	<ul>
		<% an_account.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %> 
	</ul>
</div>
<% end %>
<div class="newaccountform">
	<%= form_for an_account, url: path do |f| %> 
		<br>
			<%= f.label :name, class: 'formfield' %>
			<%= f.text_field :name, class: 'formfield' %> 
			<p>This name will be referenced when performing calculations</p> 
		<br>

		<br>
			<%= f.label :category, class: 'formfield' %>
			<%= f.text_field :category, class: 'formfield' %> 
			<p>Examples of categories can be; Annuity, Sinking Fund, Savings, Liability, Investment, Credit</p> 
		<br>

		<br>
			<%= f.label :balance, class: 'formfield' %>
			<%= f.number_field :balance, :step => 0.001, class: 'formfield' %>
			<p>As needed, this value will be used interchangeably as present value, future value or as an annuity payment</p> 
		<br>

		<br>
			<%= f.label :interest, class: 'formfield' %>
			<%= f.number_field :interest, :step => 0.001, class: 'formfield' %> <p>This will be used accordingly as the cost of borrowing money or as accumulating interest (depending on the calculation performed) </p> 
		<br>

		<br>
			<%= f.label :compounding_frequency, class: 'formfield' %>
			<%= f.number_field :compounding_frequency, class: 'formfield' %>
			<p>Interest can be compounded either; monthly, yearly, quarterly or even daily. (respective values; 12, 4, 365)</p> 
		<br>

		<br>
			<%= f.label :compounding_periods, class: 'formfield' %>
			<%= f.number_field :compounding_periods, class: 'formfield' %> 
			<p>Given the above frequency, for how many periods would interest be compounded for. Example, if interest is compounded monthly (compounding frequency; 12) and it would be in an account for 2 years; compounding periods would be 24 (12 x 2)</p> 
		<br>

		
			<%= f.submit "Save", class: 'button' %>
		
</div>
<% end %> 

fincal-railed/app/views/accounts/_quote.html.erb
<br>
<div>
	<p class="quote"><%= quote %></p>
</div>

fincal-railed/app/views/accounts/_single_account.html.erb
<% if style > 0 %>
  <div class="full_view_account">
    <h2 class="accountname">name: <%= link_to an_account.name, users_account_path(an_account) %></h2>
    <h3 class="accounttype">type: <%= an_account.category %></h3>
    <h4 class="balance">balance: $<%= number_with_delimiter(an_account.balance, :delimiter => ',') %></h4>
    <br>
    <strong class="interestrate">
      Interest rate: <%= an_account.interest %>%

    </strong>
    <h5 class="compounding">
      compounding frequency: <%= an_account.compounding_frequency%> |
      periods: <%= an_account.compounding_periods %>
    </h5>
    <p class="lastupdate">last updated on: <%= an_account.updated_at.strftime("%Y-%m-%d") %> </p>
    <div class="accountcontrol">
      <%= link_to 'Edit', edit_users_account_path %>
      <%= link_to 'Delete Account', users_account_path(@account), method: :delete, data: {confirm: "are you sure you want to delete this '#{@account.category}' account?"} %>
    </div>
  </div>
<% else %>

  <div class="account">

  	<h2 class="accountname"><%= link_to an_account.name, users_account_path(an_account) %></h2>
  	<h3 class="accounttype">type: <%= an_account.category %></h3>
  	<h4 class="balance">balance: $<%= number_with_delimiter(an_account.balance, :delimiter => ',') %></h4>
  	<br>
  	<strong class="interestrate">
  		Interest rate: <%= an_account.interest %>%

  	</strong>
  	<h5 class="compounding">
  		compounding frequency: <%= an_account.compounding_frequency%> |
  		periods: <%= an_account.compounding_periods %>
  	</h5>
  	<p class="lastupdate">last updated on: <%= an_account.updated_at.strftime("%Y-%m-%d") %> </p>
  </div>



<% end %>
<% if params[:id] %>
 <%= render 'quote', quote: User.quotes %>
<% end %>

fincal-railed/app/views/accounts/edit.html.erb
<h1> Edit <%= link_to @account.name, users_account_path(@account) %>
	
</h1>
<%= render 'account_form', an_account: @account, path: users_account_path(@account) %> 

fincal-railed/app/views/accounts/index.html.erb
<title><%= @title %></title>
<h1> Accounts </h1>
<div class="addnewaccount">
<%= link_to raw("Add New Account"), new_users_account_path%>
</div>



<div class="accountsblock">

<% @accounts.each do |account| %>
	<%= render 'single_account', an_account: account, style: 0 %>
<% end %>

</div>

fincal-railed/app/views/accounts/new.html.erb
<h1>Create New Account</h1>

<%= render 'account_form', an_account: @account, path: users_accounts_path %>

fincal-railed/app/views/accounts/real_time_tvom.html.erb
<h2>Calculate In Real Time</h2>

<h3 class="calculationinfo">Given interest portion, calculate interest rate earned over a given period</h3>
<div class="form">
  <%= form_for :compute_interest_rate,   url:real_time_tvom_results_path do |f| %>
  Interest earned in dollars: <%= f.number_field :interest_portion, :step => 0.001, class: 'formfield' %> 
  present value: <%= f.number_field :pv, class: 'formfield' %> 
  time in days: <%= f.number_field :time, class: 'formfield' %>
  <div class="buttonwrapper">
    <%= f.submit "Compute interest rate", class: 'button' %>
  </div>
  <% end %>
</div>
<br>
<br>

<h3 class="calculationinfo">Given interest rate and future value, calculate size of annuity payment needed to accumulate that future sum </h3>

<div class="formfield">
  <%= form_for :compute_annuity_payment, url:real_time_tvom_results_path do |f| %>
  Interest Rate: <%= f.number_field :interest_rate, :step => 0.001, class: 'formfield' %> 
  Compounding Frequency: <%= f.number_field :compounding_frequency, class: 'formfield' %>
  Compounding Periods: <%= f.number_field :compounding_periods, class: 'formfield' %>
  Future Value: <%= f.number_field :fv, class: 'formfield' %>
  <div class="buttonwrapper">
    <%= f.submit "Compute interest rate", class: 'button' %>
  </div>
    <% end %>
</div>

fincal-railed/app/views/accounts/real_time_tvom_results.html.erb
<h2>results</h2>
<% if params[:compute_interest_rate] %>
  <div class="tvomfinalresult">
  	<p>
  	<%= @computation %>% interest earned in <%= @real_time_account.compounding_periods %> days
  	</p>

  	<p>
  	where Present Value was	$<%= @real_time_account.balance %>
  	</p>
  </div>
<% else %>
  <div class="tvomfinalresult">
    <p>
      Given a time value of <%= @real_time_account.interest %>% interest, if you save $<%= @computation %> once every period for <%= @real_time_account.compounding_periods %> periods you will accumulate $<%= number_with_delimiter(@real_time_account.balance, :delimiter => ',') %>
    </p>
  </div>
  <div class="tvomfinalresult">
    <p>
    Total amount of interest earned during the stream of annuity payments: $<%= number_with_delimiter(@earned_amount_interest.round(2), :delimiter => ',') %>
    </p>
  </div>
<% end %>

fincal-railed/app/views/accounts/show.html.erb
<h2>created on: <%= @creation_date %></h2>




<%= render 'single_account', an_account: @account, style: 1 %>

fincal-railed/app/views/accounts/tvom.html.erb
<h1> Calculate Time Value For Your Accounts</h1>
<div class="tvomchoices">
	<%= form_for :user_choice, url: tvom_choice_path  do |f|%>
	<%= f.collection_select(:account,@accounts.all, :id, :name ) %>
	 <%= f.select :choice, [['Calculate future value', 1],['Calculate present value', 2],['calculate future value annuity',3],['Calculate present value annuity', 4]] %>
	 <%= f.submit 'Calculate' %>
</div>
<div class="realtimecalculations">
	<%= link_to 'Real Time Interest Calculations', real_time_tvom_path %>
</div>
 <br>
<h2 class="tvomcalculationheading">Possible calculations</h2>
 	<ul>
 		<li class="calculationinfo">Future Value</li>
 			<p class="calculationpara">Given present value calculate future value by accumulating interest</p>
 		<li class="calculationinfo">Present Value</li>
 			<p class="calculationpara">Given future value calculate present value by discounting interest</p>
 		<li class="calculationinfo">Future Value Annuity</li>
 			<p class="calculationpara">Given equal monthly payments calculate the future value of a series of annuity payments by accumulating interest. Annuity payment value is derived from the balance in the account.</p>
 		<li class="calculationinfo">Present Value Annuity</li>
 			<p class="calculationpara">Given equal monthly payments to be made in the future calculate the present value of a series of annuity payments by discounting interest. Annuity payment value is derived from the balance in the account.</p>
 	</ul>
<% end %>



<div class="tvomupgradewrapper">
	<h3 class="tvomupgrades">Future upgrades</h3>
		<ul>
			<li> Overhauled user experience, bringing Fincal from 2001, to 2018</li>
      <li>Email notifications</li>
		</ul>
</div>

fincal-railed/app/views/accounts/tvom_results.html.erb
<div class="tvomresult">
<% if @selection < 5 %>
		<% if @interest_portion > 0 %>
			<p> you earned $<%= number_with_delimiter(@interest_portion, :delimiter => ',') %> of interest, in <%= @interest_time %> periods, where interest was compounded
				<% if @frequency == 1 %>
					<strong>once a year</strong>
				<% else %>
					<strong>
						<%= @frequency %>
						times a year
					</strong>
				<% end %>
			</p>
		<% else %>
			<p> you discounted $<%= number_with_delimiter(@interest_portion.abs, :delimiter => ',')%> of interest, in <%= @interest_time %> periods, where interest was compounded
				<% if @frequency == 1 %>
					<strong>once a year</strong>
				<% else %>
					<strong>
						<%= @frequency %>
						times a year
					</strong>
					<% end %>
			</p>
		<% end %>
	<% end %>
</div>

<div class="tvomfinalresult">
	<strong>
		<%= @calculation_performed %>
			<% if @selection >= 5 %>
			<%= number_with_delimiter(@result, :delimiter => ',') %>%
			<% else %>

		$<%= number_with_delimiter(@result, :delimiter => ',') %>
			<% end %>
	</strong>
</div>