fincal-railed/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

# # Resource Routes  
# 	resources :users, only: %i(create update destroy)
#   	resources :sessions, only: %i(create)

#   	#Manuall Routes
#   	#Main Routes
  	root 'users#welcome'

#   	#User Routes
#   	get '/user/profile' => 'users#profile'
#   	get '/login' => 'users#login'
#   	get '/signup' => 'users#new'
#     post '/user/updatepassword' => 'users#changePassword'

#     #Sessions Routes
#     get 'session/destroy' => 'sessions#destroy'

#   root 'main#index'
   get '/tvom' => 'accounts#tvom' #, as: :tvom_landing
   get '/tvom/real-time-tvom' => 'accounts#real_time_tvom', as: :real_time_tvom
   post '/tvom/real-time-tvom/real-time-tvom-results' => 'accounts#real_time_tvom_results', as: :real_time_tvom_results

#   resources :accounts 
	post '/tvom/results' => 'accounts#tvom_results', as: :tvom_choice

	get '/about' => 'users#about', as: :about
	
resource :users, only: %i(new create update destroy) do
  resources :accounts
end

#maybe this resource needs to be singular?
resource :sessions, only: [:new, :create, :destroy]




end

fincal-railed/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <div class="title">
    <title><%= @title %></title>
    </div>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <h1>
    <%= link_to "MyFincal", root_path %>
  </h1>
  <header class="actionheader">
        <% if current_user %>

          <div class="usergreeting">
          <strong> Hello, <%= current_user.first_name.capitalize %></strong>
          <div class="logout">
          <%= link_to 'Log Out', sessions_path, method: :delete %>
          </div>
          </div>
          <div class="topribbon">
            	<%= link_to raw("&#x2655;Accounts&#x2655;"), users_accounts_path %>
          	<%= link_to raw("&#x24;Time Value of Money&#x24;"), tvom_path%>
            <%= link_to raw('&#x029C0;about&#x029C1;'), about_path %>
          </div>

        <% else %>
          <div class="topribbon" id="topRibbon">
            <%= link_to 'New Account', new_users_path %>
            <%= link_to 'Login', new_sessions_path,id: 'loginButton' %>
             <%= link_to 'about', about_path %>
          </div>
            <div id="loginbox">

              <br>
              <%= form_for :session, url: sessions_path do |f| %>
                <div class="form">
                  <%= f.label :email, class: 'formfield' %> 
                  <%= f.text_field :email, class: 'formfield' %> 
                </div>

                <div class="form">
                  <%= f.label :password, class: 'formfield' %> 
                  <%= f.password_field :password, class: 'formfield' %> 
                </div>

                <div class="buttonwrapper">
                  <%= f.submit 'log in', class: 'button' %>
                </div>
              <% end %>
            </div>

           
          
        <% end %>
  </header>
  <body>
    <%= yield %>
  </body>
  <footer>
    <p>New Updates Released Weekly</p>
  </footer>
</html>