fincal-railed/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

# # Resource Routes  
# 	resources :users, only: %i(create update destroy)
#   	resources :sessions, only: %i(create)

#   	#Manuall Routes
#   	#Main Routes
  	root 'users#welcome'

#   	#User Routes
#   	get '/user/profile' => 'users#profile'
#   	get '/login' => 'users#login'
#   	get '/signup' => 'users#new'
#     post '/user/updatepassword' => 'users#changePassword'

#     #Sessions Routes
#     get 'session/destroy' => 'sessions#destroy'

#   root 'main#index'
   get '/tvom' => 'accounts#tvom' #, as: :tvom_landing
   get '/tvom/real-time-tvom' => 'accounts#real_time_tvom', as: :real_time_tvom
   post '/tvom/real-time-tvom/real-time-tvom-results' => 'accounts#real_time_tvom_results', as: :real_time_tvom_results

#   resources :accounts 
	post '/tvom/results' => 'accounts#tvom_results', as: :tvom_choice

	get '/about' => 'users#about', as: :about
	
resource :users, only: %i(new create update destroy) do
  resources :accounts
end

#maybe this resource needs to be singular?
resource :sessions, only: [:new, :create, :destroy]




end

fincal-railed/app/models/user.rb
class User < ApplicationRecord
	has_many :accounts
	
	has_secure_password

	PASSWORD_FORMAT = /\A
	  (?=.{6,})          # Must contain 6 or more characters
	  (?=.*\d)           # Must contain a digit
	  (?=.*[a-z])        # Must contain a lower case character
	  (?=.*[A-Z])        # Must contain an upper case character
	  						# Must contain a symbol   
	/x

	# (?=.*[[:^alnum:]])

	validates :password, presence: true, length: {:within => 6..40}, format: { with: /\A(?=.{6,})/, message: "length minimum 6 characters"  }, confirmation: true, on: :create
	validates :password, presence: true, length: {:within => 6..40}, format: { with: /\A(?=.*\d)/, message: "must contain a digit"  }, confirmation: true, on: :create
	validates :password, presence: true, length: {:within => 6..40}, format: { with: /\A(?=.*[a-z])/, message: "must contain lower case character"  }, confirmation: true, on: :create
	validates :password, presence: true, length: {:within => 6..40}, format: { with: /\A(?=.*[A-Z])/, message: "must contain uppercase character"  }, confirmation: true, on: :create

	validates :password, allow_nil: true, length: {:within => 6..40}, format: { with: PASSWORD_FORMAT }, confirmation: true, on: :update

	validates :email, presence: true, uniqueness: true
	validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/

	validates :username, presence: true, uniqueness: true, format: { with: /\A[a-zA-Z0-9]+\z/,message: "Only letters and Numbers are allowed" }

	validates :first_name,presence: true, format: { with: /\A[a-zA-Z]+\z/,message: "Only letters are allowed" }
    validates :last_name,presence: true, format: { with: /\A[a-zA-Z]+\z/,message: "Only letters are allowed" }

    def self.quotes
    	quotes = ["Labour was the first price, the original purchase - money that was paid for all things. It was not by gold or by silver, but by labour, that all wealth of the world was originally purchased - Adam Smith", 
    		"Science is the great antidote to the poison of enthusiasm and superstition - Adam Smith", "Science is the great antidote to the poison of enthusiasm and superstition - Adam Smith", 
    		"This is one  ofthose cases in which the imagination is baffled by the facts - Adam Smith", 
    		"Capitalism is the astounding belief that the most wickedest of men will do the most wickedest of things for the greatest good of everyone - John Maynard Keynes", 
    		"By a continuing process of inflation, government can confiscate, secretly and unobserved, an important part of the wealth of their citizens - John Maynard Keynes", 
    		"The only relevant test of the validity of a hypothesis is comparison of prediction with experience.- Milton Friedman"]

    	random_quote = quotes.sample
    	return random_quote
    end 	 
end

fincal-railed/app/controllers/users_controller.rb
class UsersController < ApplicationController

  # Make Sure user is logged in
  before_action :require_login, only: %i(profile update changePassword)
  before_action :already_logged_in, only: %i(new login)
  def profile
    @user = current_user
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	# If user get saved to database
    #respond_to do |format|
    	if @user.save
        session[:user_id] = @user.id

        UserMailer.with(user: @user).welcome_email(@user).deliver_now
        
        #format.html {redirect_to users_accounts_path}
    		redirect_to users_accounts_path
    	else
    	#If there is error while saving to database
    		render :new
    	end
    #end

  end


  def update
    if current_user.update_attributes(user_update_params)
      #set Message
    else
      #set Message
    end

    redirect_to user_profile_path

  end


  def changePassword
     user = User.find_by_username(current_user.username)
      # If the user exists AND the password entered is correct.
      if user && user.authenticate(params[:update_password][:old_password]) && params[:update_password][:password] == params[:update_password][:password_confirmation]
        user.password = params[:update_password][:password]
        if user.save
          #set Message
        else
          #set Message
        end
      else
       # set Message; Password dosn't match with confirm
      end
      redirect_to user_profile_path
  end

  def login 
  	@user = User.new
  end

 
  def destroy

    if current_user.delete
      redirect_to root_path
    else
     #Edit Message
     redirect_to user_profile_path
    end

  end

  

  def about 
    render :about
  end 

  private

  def user_params
  	params.require(:user).permit(:first_name,:last_name,:username,:email,:password,:password_confirmation)
  end

  def user_update_params
    params.require(:user).permit(:first_name,:last_name,:username,:email)
  end

end

fincal-railed/app/views/users/about.html.erb
<h1 class="aboutheadline">not that anyone asked, but I decided to share some thoughts about this app here</h1>
<div class="aboutlinks">
	<a href="https://github.com/donrestarone/Fincal-lib">source code</a>
	<br>
	<p>Contact: myfincal@gmail.com</p>

</div>
	<h2>
		What was the motivation behind creating this app?
	</h2>
<p class="aboutbody">
	The answer to this is twofold. First, I needed a small project I could work on when I rekindled my love for programming. At the time it seemed like a good idea, since I was trying to save up money and be more financially responsible. The early command line version was terrible, with no classes being used and no data persistence. As i went along, I began to apply skills I learned at Bitmaker and implemented design principals that I was exposed to. Gradually, Fincal gained classes and methods, and was eventually moved on to Sinatra. After learning Rails, I decided it would be a good idea to put it on Rails since I desired to deploy it and implement some business logic that would derive its data from a PostgresDB. Note that till the Rails implementation, its mathematical functions were limited to the command line version.
</p>
<p class="aboutbody">
		The second, and more opinionated reason is that I think people my age tend to be less concerned with long term consequences and more focused on short term contentments when it comes to being fiscally responsible. I believe that most of the personal financial planning (i.e figuring out if you can afford something, estimating how long you need to save so you can responsibly buy something extravagant etc) can be achieved with some basic math/accounting skills and a financial calculator. But there has to be an easier way, financial calculators tend to have a learning curve and present digital offerings are complicated, often distracting you from your current focus.
</p>


	<h2>
		What is in store for the future?
	</h2>
<p class="aboutbody">
	Hopefully, a better user interface that leads to a decent user experience. I'm planning on revamping the backend to be more of an API, so that the website front-end and mobile app (when I get around to learning Swift) can simply make requests to the server and have everything run smoothly.
</p>

	<h2>
		Any goals for this app?
	</h2>
<p class="aboutbody">
	Frankly I'd be ecstatic if even one person and/or a llama somewhere used Fincal to plan something related to their personal finances.
</p>

fincal-railed/app/views/users/new.html.erb
<h2>Create New Account</h2>


<!-- Display Error Message if User didn't saved -->

  <% if @user.errors.any? %>
    <div class="errors">
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <% end %>



<% if flash[:warning] %>
  <% flash[:warning].each do |error| %>
    <%= error %> 
  <% end %> 
<% end %>
<!-- End Error Message -->

<div class="newaccountform">
  <%= form_for @user do |f| %>
    <%= f.label :first_name, class: 'formfield' %>: 
    <%= f.text_field :first_name, placeholder: "letters only", class: 'formfield' %><br />

    <%= f.label :last_name, class: 'formfield' %>:
    <%= f.text_field :last_name, placeholder: "letters only", class: 'formfield' %><br />

    <%= f.label :username, class: 'formfield' %>:
    <%= f.text_field :username, class: 'formfield' %><br />

    <%= f.label :email, class: 'formfield' %>:
    <%= f.text_field :email, class: 'formfield' %><br />
      
      <div class="passconditions">
        <strong>password conditions</strong>
        <ul>
          <li>must contain 6 or more characters</li>
          <li>must contain a digit</li>
          <li>must contain a lower case character</li>
          <li>must contain an uppercase character</li>
          <li>symbols are optional, for your mental sanity</li>
        </ul>
      </div>

    <%= f.label :password, class: 'formfield' %>:
    <%= f.password_field :password, class: 'formfield' %><br />

    <%= f.label :password_confirmation, class: 'formfield' %>:
    <%= f.password_field :password_confirmation, class: 'formfield' %><br />


    <%= f.submit %>
  </div>
  <% end %>

fincal-railed/app/views/users/profile.html.erb
<h1>User#profie</h1>
<p>Find me in app/views/user/profie.html.erb</p>
<%= link_to "Logout", session_destroy_path%>


<%= form_for @user do |f| %>

  <%= f.label :first_name %>:
  <%= f.text_field :first_name, value: @user.first_name%><br />

  <%= f.label :last_name %>:
  <%= f.text_field :last_name, value: @user.last_name %><br />

  <%= f.label :username %>:
  <%= f.text_field :username, value: @user.username %><br />

  <%= f.label :email %>:
  <%= f.text_field :email, value: @user.email %><br />


  <%= f.submit %>
<% end %>

Update Password


<%= form_for :update_password, url: user_updatepassword_path  do |f| %>

	<%= f.label :old_password %>:
 	<%= f.password_field :old_password %><br />

	<%= f.label :password %>:
	<%= f.password_field :password %><br />

	<%= f.label :password_confirmation %>:
	<%= f.password_field :password_confirmation %><br />

	<%= f.submit %>
<% end %>


<%= link_to "Delete Account", @user, method: :delete,  data: { confirm: "Are you sure?" }%>

fincal-railed/app/views/users/welcome.html.erb
<main>
<h2 class='fincalwelcome'>Your personal financial planner, database and manager</h2>


	<div class="welcomeinformation">
    <p>
      In a device-driven world where conveneince, spontaneity and speed are always on our minds, lets take a moment to pull back from swiping and 'Tap to Pay' to consider and plan our finances.
    </p>
    <br>
    <p>
      Ever wondered how much interest you would owe at the end of a financing term? Or how much you would need to put away monthly to retire comfortably in 20 or so years? you can use Fincal to figure out the answers to these questions.
    </p>
    <br>
    <p>
      To make calculations and accumulate/discount interest rates/values please sign up. Documentation is provided on the add account page, and Time Value Of Money page on how to use the app.
    </p>
	</div>

	<div class="welcomeabout">
		<p>Caffeinated development by <a href="https://www.linkedin.com/in/shashike-jayatunge">Shashike J</a></p>
		<p>Special thanks to <a href="https://www.linkedin.com/in/gurjantsadhra/">Gurjant Singh Sadhra</a> for his guidance</p>
	</div>

	<div class="cryptobox">
		<ul>
			<% if @coins %>
				<% @coins.each do |coin| %>
						<li>
							<ul>
								<div class="coin">
									<br>
									<div class="singleCoin">
									<p class="coinName"><%= coin['name'] %></p>
									<p>price: $<span class="coinPrice"><%= coin['price'] %></span></p>
									</div>
									

									<p>percent change in 24h <span class="changeIn24h"><%= coin['percent_change_24h'] %></span></p>
									<p>percent change in 7 days <span class="changeIn7d"><%= coin['percent_change_7_days'] %></span></p>
									<% if coin['equivalent_rate_24h'].to_i > 0 %>
										<div class="cryptogreen">
										<p>earned an equivalent rate: <%= coin['equivalent_rate_24h'] %>% in 24 hours</p>
										</div>
									<% elsif coin['equivalent_rate_24h'].to_i < 0 %>
										<div class="cryptored">
										<p>discounted an equivalent rate: <%= coin['equivalent_rate_24h'] %>% in 24 hours</p>
										</div>
									<% end %>

									<% if coin['equivalent_rate_7d'].to_i > 0 %>
										<div class="cryptogreen">
										<p>earned an equivalent rate: <%= coin['equivalent_rate_7d'] %>% in 7 days</p>
										</div>
									<% elsif coin['equivalent_rate_7d'].to_i < 0 %>
										<div class="cryptored">
										<p>discounted an equivalent rate: <%= coin['equivalent_rate_7d'] %>% in 7 days</p>
										</div>
									<% end %>
									<br>
								</div>
							</ul>
						</li>
				<% end %>
			<% else %>
				<p>Coin Market Cap API down</p>
				<br>
			<% end %>
		</ul>
	</div>

	<div class="quotebox">
		<p class="quote"><%= @welcome_quote %></p>
	</div>

	<div versionupdate>
		<p>version: <%= @version %></p>
		<p>last update: <%= @update_date %></p>
	</div>
</main>